# -*- coding: utf-8 -*-
"""STAGE - All Transactions - Senators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KoswL9U-vOOjL6wtmKRTivL0nZOTqK1V

# INITIALIZATION
"""

import pandas as pd
import numpy as np
import os, shutil

from datetime import datetime

from google.colab import drive
drive.mount('/content/drive')

src_dir = "/content/drive/MyDrive/Projects/00 - Data Drop/House & Senate Stock Tracking/"

tgt_dir_hist = "/content/drive/MyDrive/Projects/01 - Data Staging/House & Senate Stock Tracking/All Transactions - Senators/historical/"
tgt_dir_tost = "/content/drive/MyDrive/Projects/01 - Data Staging/House & Senate Stock Tracking/All Transactions - Senators/top-of-stack/"

"""# SCRIPT

## Read Raw Data
"""

senate_raw = pd.read_json("https://senate-stock-watcher-data.s3-us-west-2.amazonaws.com/aggregate/all_transactions.json")

date_string = datetime.today().strftime('%Y-%m-%d')

"""## Save Copy of Raw Data to Appropriate Historical Folder"""

senate_raw.to_csv(tgt_dir_hist + "all_transactions_senate_" + date_string + ".csv",index=False)

"""## Delete All Files in Appropriate Top of Stack Directory"""

# DELETE ALL FILES IN THE TOP-OF-STACK DIRECTORY

for filename in os.listdir(tgt_dir_tost):
    file_path = os.path.join(tgt_dir_tost, filename)
    try:
        if os.path.isfile(file_path) or os.path.islink(file_path):
            os.unlink(file_path)
        elif os.path.isdir(file_path):
            shutil.rmtree(file_path)
    except Exception as e:
        print('Failed to delete %s. Reason: %s' % (file_path, e))

"""## Save Copy of Raw Data to Appropriate Top of Stack Folder"""

senate_raw.to_csv(tgt_dir_tost + "all_transactions_senate_" + date_string + ".csv",index=False)